<a href="https://colab.research.google.com/github/DxubleBTW/averylee-money-market-funds-analysis/blob/main/AveryLeeFinanceNotebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

url = "https://raw.githubusercontent.com/DxubleBTW/averylee-money-market-funds-analysis/refs/heads/main/mmf-2026-04.csv"

df = pd.read_csv(url)

df.head()

,ReportMonth,registrant_cik,registrant,series_name,series_id,series_category,class_name,class_id,investment_advisor,class_ticker_symbol,sub_advisor
0,2026-04-30,742212,"NORTHWESTERN MUTUAL SERIES FUND, INC.",GOVERNMENT MONEY MARKET PORTFOLIO,S000000048,Government,Government Money Market Portfolio,C000000083,"Mason Street Advisors, LLC",NaN,"BlackRock Advisors, LLC"
1,2026-04-30,796251,DREYFUS TREASURY &AMP;AMP;AMP; AGENCY CASH MAN...,DREYFUS TREASURY OBLIGATIONS CASH MANAGEMENT,S000000112,Government,Institutional Shares,C000000251,"BNY Mellon Investment Adviser, Inc.",DTRXX,NaN
2,2026-04-30,796251,DREYFUS TREASURY &AMP;AMP;AMP; AGENCY CASH MAN...,DREYFUS TREASURY OBLIGATIONS CASH MANAGEMENT,S000000112,Government,Investor Shares,C000000252,"BNY Mellon Investment Adviser, Inc.",DTVXX,NaN
3,2026-04-30,796251,DREYFUS TREASURY &AMP;AMP;AMP; AGENCY CASH MAN...,DREYFUS TREASURY OBLIGATIONS CASH MANAGEMENT,S000000112,Government,Administrative Shares,C000000253,"BNY Mellon Investment Adviser, Inc.",DTAXX,NaN
4,2026-04-30,796251,DREYFUS TREASURY &AMP;AMP;AMP; AGENCY CASH MAN...,DREYFUS TREASURY OBLIGATIONS CASH MANAGEMENT,S000000112,Government,Participant Shares,C000000254,"BNY Mellon Investment Adviser, Inc.",DTPXX,NaN

# Money Market Funds Analysis
### Columbia Data Science Research Program
By: Avery Lee

## Checkpoint 1: Data Cleaning

This notebook explores the April 2026 SEC Money Market Fund dataset. The goal of this notebook is to clean the data.

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", None)

In [4]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 1206
Columns: 11

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1206 entries, 0 to 1205
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ReportMonth          1206 non-null   object
 1   registrant_cik       1206 non-null   int64
 2   registrant           1206 non-null   object
 3   series_name          1206 non-null   object
 4   series_id            1206 non-null   object
 5   series_category      1206 non-null   object
 6   class_name           1206 non-null   object
 7   class_id             1206 non-null   object
 8   investment_advisor   1206 non-null   object
 9   class_ticker_symbol  996 non-null    object
 10  sub_advisor          394 non-null    object
dtypes: int64(1), object(10)
memory usage: 103.8+ KB

In [6]:
df.columns = (
    df.columns
      .str.lower()
      .str.strip()
      .str.replace(" ", "_")
)

df.columns

Index(['reportmonth', 'registrant_cik', 'registrant', 'series_name',
       'series_id', 'series_category', 'class_name', 'class_id',
       'investment_advisor', 'class_ticker_symbol', 'sub_advisor'],
      dtype='object')

In [7]:
df.isnull().sum()

reportmonth              0
registrant_cik           0
registrant               0
series_name              0
series_id                0
series_category          0
class_name               0
class_id                 0
investment_advisor       0
class_ticker_symbol    210
sub_advisor            812
dtype: int64

In [8]:
duplicates = df.duplicated().sum()

print("Duplicate rows:", duplicates)

Duplicate rows: 0

In [9]:
print("Unique Registrants:", df["registrant"].nunique())

print("Unique Fund Series:", df["series_id"].nunique())

print("Unique Share Classes:", df["class_id"].nunique())

print("Fund Categories:")
print(df["series_category"].value_counts())

Unique Registrants: 187
Unique Fund Series: 320
Unique Share Classes: 1048
Fund Categories:
series_category
Government          869
Prime               160
Other Tax Exempt    102
Single State         75
Name: count, dtype: int64

In [10]:
text_columns = [
    "registrant",
    "series_name",
    "series_category",
    "class_name",
    "investment_advisor",
    "sub_advisor"
]

for col in text_columns:
    df[col] = df[col].str.strip()

df.head()

,reportmonth,registrant_cik,registrant,series_name,series_id,series_category,class_name,class_id,investment_advisor,class_ticker_symbol,sub_advisor
0,2026-04-30,742212,"NORTHWESTERN MUTUAL SERIES FUND, INC.",GOVERNMENT MONEY MARKET PORTFOLIO,S000000048,Government,Government Money Market Portfolio,C000000083,"Mason Street Advisors, LLC",NaN,"BlackRock Advisors, LLC"
1,2026-04-30,796251,DREYFUS TREASURY &AMP;AMP;AMP; AGENCY CASH MAN...,DREYFUS TREASURY OBLIGATIONS CASH MANAGEMENT,S000000112,Government,Institutional Shares,C000000251,"BNY Mellon Investment Adviser, Inc.",DTRXX,NaN
2,2026-04-30,796251,DREYFUS TREASURY &AMP;AMP;AMP; AGENCY CASH MAN...,DREYFUS TREASURY OBLIGATIONS CASH MANAGEMENT,S000000112,Government,Investor Shares,C000000252,"BNY Mellon Investment Adviser, Inc.",DTVXX,NaN
3,2026-04-30,796251,DREYFUS TREASURY &AMP;AMP;AMP; AGENCY CASH MAN...,DREYFUS TREASURY OBLIGATIONS CASH MANAGEMENT,S000000112,Government,Administrative Shares,C000000253,"BNY Mellon Investment Adviser, Inc.",DTAXX,NaN
4,2026-04-30,796251,DREYFUS TREASURY &AMP;AMP;AMP; AGENCY CASH MAN...,DREYFUS TREASURY OBLIGATIONS CASH MANAGEMENT,S000000112,Government,Participant Shares,C000000254,"BNY Mellon Investment Adviser, Inc.",DTPXX,NaN

In [11]:
df.to_csv("cleaned_mmf_2026_04.csv", index=False)

## Data Cleaning Summary

The SEC Money Market Fund dataset was imported into Google Colab directly from GitHub. The column names were standardized by converting them to lowercase and replacing spaces with underscores for consistency. Missing values were examined, and no rows were removed because missing ticker symbols and sub-advisors represent legitimate missing information rather than data errors. The dataset contained no duplicate rows and was confirmed to already be in tidy format, with each row representing a single share class and each column representing a single variable.